name = "createpak"
author = "ldez"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ddcf98aa3beb2c9f96b1a49213155c0ef2624b871b6bd9a04c6d98bb1d01b468"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
