name = "createpak"
author = "ldez"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aaad09581fde34db59cf78bb6b72bf506c6c9e90c5f57e5241f9c4edeb4d9b30"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
