name: Export Modpack

on:
  push:
    branches: [ "main" ]
  release:
    types: [created]

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Packwiz
        run: |
          curl -L -o packwiz.zip https://nightly.link/packwiz/packwiz/workflows/go/master/packwiz-linux-64.zip
          unzip packwiz.zip
          chmod +x packwiz
          sudo mv packwiz /usr/local/bin/

      - name: Refresh modpack index
        run: packwiz -y refresh

      - name: Export to CurseForge
        run: packwiz -y curseforge export -o curseforge.zip

      - name: Export to Modrinth
        run: packwiz -y modrinth export -o modrinth.mrpack

      - uses: actions/upload-artifact@v4
        with:
          name: modpack-exports
          path: |
            curseforge.zip
            modrinth.mrpack 