name: Export Modpack

on:
  push:
    branches: [ "main" ]
  release:
    types: [created]

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for changelog generation

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install Packwiz
        run: |
          go install github.com/packwiz/packwiz@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Generate changelog
        if: github.event_name == 'release'
        id: changelog
        run: |
          # Get the current tag and find previous tag
          CURRENT_TAG=${GITHUB_REF#refs/tags/}
          PREVIOUS_TAG=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1) 2>/dev/null || echo "")
          
          echo "Generating changelog from $PREVIOUS_TAG to $CURRENT_TAG"
          
          if [ -z "$PREVIOUS_TAG" ]; then
            # No previous tag, get all commits
            CHANGELOG=$(git log --pretty=format:"* %s (%h)" $CURRENT_TAG)
          else
            # Get commits between tags
            CHANGELOG=$(git log --pretty=format:"* %s (%h)" $PREVIOUS_TAG..$CURRENT_TAG)
          fi
          
          # Save changelog to file
          echo "$CHANGELOG" > changelog.md
          
          # Create multiline output for GitHub Actions
          CHANGELOG="${CHANGELOG//'%'/'%25'}"
          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
          
          echo "changelog=$CHANGELOG" >> $GITHUB_OUTPUT

      - name: Export CurseForge Pack
        run: |
          cd curseforge
          if [ ! -f "pack.toml" ]; then
            echo "Error: pack.toml not found in curseforge directory"
            ls -la
            exit 1
          fi
          packwiz -y refresh
          packwiz -y curseforge export -o ../curseforge.zip

      - name: Export Modrinth Pack
        run: |
          cd modrinth
          if [ ! -f "pack.toml" ]; then
            echo "Error: pack.toml not found in modrinth directory"
            ls -la
            exit 1
          fi
          packwiz -y refresh
          packwiz -y modrinth export -o ../modrinth.mrpack

      - uses: actions/upload-artifact@v4
        with:
          name: modpack-exports
          path: |
            curseforge.zip
            modrinth.mrpack
            changelog.md

      - name: Upload Release Assets
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            curseforge.zip
            modrinth.mrpack
            changelog.md
          body_path: changelog.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 